name: Build and Push to Docker
on:
    push:
        branches:
            - "main"
    workflow_dispatch:
jobs:
    cd-staging:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: "./.github/actions"
              with:
                  docker-username: ${{ secrets.DOCKER_USERNAME }}
                  docker-password: ${{ secrets.DOCKER_PASSWORD }}
                  docker-repository: "kube-netlag"
                  version-label: 1.0.0
